services:
  # Pi-hole service
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - WEBPASSWORD=password
      - PIHOLE_DNS_=8.8.8.8 # Use Google DNS or another DNS of your choice
      - PIHOLE_INTERFACE=eth0
      - VIRTUAL_HOST=pihole.local
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      - pihole_network

  # Fail2Ban service
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    volumes:
      - ./fail2ban:/etc/fail2ban
      - /var/log:/var/log
    networks:
      - pihole_network
    environment:
      - TZ=Europe/London

  # Portainer (Dashboard) for Docker management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    environment:
      - TZ=Europe/London
    ports:
      - "9000:9000"  # Port to access the dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - pihole_network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  # Prometheus UI port
    volumes:
      - ./prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - pihole_network

  # Grafana for data visualization (connected to Prometheus)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password  # Change the default admin password
    ports:
      - "3000:3000"  # Grafana dashboard
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - pihole_network

  # System metrics
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - pihole_network
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  # Monitor endpoints
  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - pihole_network
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

networks:
  pihole_network:
    driver: bridge